dist: trusty
sudo: required

language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  # - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

before_install:
 - sudo apt-get update -y
 - sudo apt-get install -y libgdal-dev libproj-dev libproj-dev spatialite-bin python-dev python3-dev

install:
 - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite; fi
   # This is a dependency of our Django test script
 - CFLAGS=-I/usr/include/gdal pip install GDAL==1.10

 - pip install jsonfield
 - pip install argparse
 - pip install -q Django==$DJANGO_VERSION
 - pip install coverage
 - pip install flake8
 - pip install coveralls
 - python setup.py develop

before_script:
 - flake8 --ignore=E501 djgeojson

script:
 - coverage run quicktest.py djgeojson

after_success:
 - coveralls

matrix:
    exclude:
        - python: 3.4
          env: DJANGO_VERSION=1.4.10
        - python: 3.5
          env: DJANGO_VERSION=1.4.10
        - python: 3.5
          env: DJANGO_VERSION=1.5.12
        - python: 3.5
          env: DJANGO_VERSION=1.6.11
        - python: 3.5
          env: DJANGO_VERSION=1.7.7
        - python: 3.5
          env: DJANGO_VERSION=1.8
